FROM ruby:3.4.4

RUN apt-get update -qq && \
    apt-get install -y postgresql-client nodejs && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["./bin/rails", "server", "-b", "0.0.0.0"]